/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GraciasRouteImport } from './routes/gracias'
import { Route as VendaRouteImport } from './routes/venda'
import { Route as VentaRouteImport } from './routes/venta'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraciasRoute = GraciasRouteImport.update({
  id: '/gracias',
  path: '/gracias',
  getParentRoute: () => rootRouteImport,
} as any)
const VendaRoute = VendaRouteImport.update({
  id: '/venda',
  path: '/venda',
  getParentRoute: () => rootRouteImport,
} as any)
const VentaRoute = VentaRouteImport.update({
  id: '/venta',
  path: '/venta',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gracias': typeof GraciasRoute
  '/venda': typeof VendaRoute
  '/venta': typeof VentaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gracias': typeof GraciasRoute
  '/venda': typeof VendaRoute
  '/venta': typeof VentaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gracias': typeof GraciasRoute
  '/venda': typeof VendaRoute
  '/venta': typeof VentaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gracias' | '/venda' | '/venta'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gracias' | '/venda' | '/venta'
  id: '__root__' | '/' | '/gracias' | '/venda' | '/venta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraciasRoute: typeof GraciasRoute
  VendaRoute: typeof VendaRoute
  VentaRoute: typeof VentaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gracias': {
      id: '/gracias'
      path: '/gracias'
      fullPath: '/gracias'
      preLoaderRoute: typeof GraciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venda': {
      id: '/venda'
      path: '/venda'
      fullPath: '/venda'
      preLoaderRoute: typeof VendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venta': {
      id: '/venta'
      path: '/venta'
      fullPath: '/venta'
      preLoaderRoute: typeof VentaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraciasRoute: GraciasRoute,
  VendaRoute: VendaRoute,
  VentaRoute: VentaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
